#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config focus_follows_pointer true

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding 28

bspc config -n $(bspc query -N -n) border_width 0

bspc rule -a border=off
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

nitrogen --restore &
picom &
#sh $HOME/.config/polybar/launch.sh 

#Network manager
nm-applet

# Set the border colors.
bspc config normal_border_color "#1f1f1f"
bspc config active_border_color "#1f1f1f"
bspc config focused_border_color "#1f1f1f"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "1f1f1f"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"&

#Commands for use with Plasma
#wmctrl -c Plasma
#ksuperkey
